# Lista de fontes padrão do Windows
FONTS = ["Arial", "Calibri", "Comic Sans MS", "Courier New", "Georgia",
          "Impact", "Tahoma", "Times New Roman", "Trebuchet MS", "Verdana",
          "Bookman Old Style", "Century Gothic", "Garamond", "Lucida Console",
          "Palatino Linotype", "Segoe UI", "Symbol", "Webdings", "Wingdings",
          "Yu Gothic", "Andale Mono", "Arial Black", "Bodoni MT",
          "Bauhaus 93", "Brush Script MT", "Candara", "Consolas",
          "Cooper Black", "Franklin Gothic Medium", "Futura", "Gill Sans",
          "Haettenschweiler", "Helvetica", "Imprint MT Shadow",
          "Lucida Handwriting", "Magneto", "Mistral", "Monotype Corsiva",
          "OCR A Extended", "Old English Text MT", "Perpetua",
          "Rockwell Extra Bold", "Segoe Print", "Showcard Gothic",
          "Stencil", "Tw Cen MT", "Wide Latin"]

# Lista de frases para escolher aleatoriamente
PHRASES = ["O cachorro late, a caravana passa.",
          "A pressa é inimiga da perfeição.",
          "Quem semeia vento colhe tempestade.",
          "De grão em grão a galinha enche o papo.",
          "Quem ri por último ri melhor.",
          "Água mole em pedra dura, tanto bate até que fura.",
          "O pior cego é o que não quer ver.",
          "Quem não tem cão caça com gato.",
          "Em boca fechada não entra mosca.",
          "A união faz a força.",
          "A esperança é a última que morre.",
          "Deus ajuda quem cedo madruga.",
          "O hábito faz o monge.",
          "Antes tarde do que nunca.",
          "Quem com ferro fere, com ferro será ferido.",
          "A necessidade é a mãe da invenção.",
          "Cada macaco no seu galho.",
          "Quem muito escolhe pouco acerta.",
          "Mais vale um pássaro na mão do que dois voando.",
          "Quando um burro fala, os outros abaixam a orelha."]